// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqUnx2VmL2FbZczqN-wXZ6cfPurZxizpM',
    appId: '1:416281920348:web:62bcfdce41e5d034f6b799',
    messagingSenderId: '416281920348',
    projectId: 'isefproject-f92d3',
    authDomain: 'isefproject-f92d3.firebaseapp.com',
    databaseURL: 'https://isefproject-f92d3-default-rtdb.firebaseio.com',
    storageBucket: 'isefproject-f92d3.appspot.com',
    measurementId: 'G-7KB8XP9B10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzEQd6GDPcCArCMbA6odcV3YPnv73cygc',
    appId: '1:416281920348:android:4693b090ca633540f6b799',
    messagingSenderId: '416281920348',
    projectId: 'isefproject-f92d3',
    databaseURL: 'https://isefproject-f92d3-default-rtdb.firebaseio.com',
    storageBucket: 'isefproject-f92d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Hje5CEucvKJKCj4b5EIwOFh8ZlPBsUw',
    appId: '1:416281920348:ios:78bec5d3abe80e85f6b799',
    messagingSenderId: '416281920348',
    projectId: 'isefproject-f92d3',
    databaseURL: 'https://isefproject-f92d3-default-rtdb.firebaseio.com',
    storageBucket: 'isefproject-f92d3.appspot.com',
    iosBundleId: 'com.example.adhd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Hje5CEucvKJKCj4b5EIwOFh8ZlPBsUw',
    appId: '1:416281920348:ios:78bec5d3abe80e85f6b799',
    messagingSenderId: '416281920348',
    projectId: 'isefproject-f92d3',
    databaseURL: 'https://isefproject-f92d3-default-rtdb.firebaseio.com',
    storageBucket: 'isefproject-f92d3.appspot.com',
    iosBundleId: 'com.example.adhd',
  );

}